### PR TITLE
Add ember-cli-deploy-redis to package.json dependencies

### PR DESCRIPTION
**Pull request by gordonbisnor**
Deploy silently fails for me without ember-cli-deploy-redis, do you agree? If so, should be a dependency and/or a note in the README….

Signed-off-by: Gordon B. Isnor <gordonbisnor@gmail.com>

### CODE REVIEW

**Comment by gordonbisnor** [comment]
@jaydev Let me know what you think here –– this is failing for me without ember-cli-deploy-redis... I could also add a note to the README about this.

**Comment by jaydev** [comment]
It's been working for me without the explicit addition of that package, but I will wipe out my `node_modules` directory and test with a fresh install.

Are you using yarn instead of npm? I noticed you added a `yarn.lock` file to the the PR.

**Comment by jaydev** [comment]
@gordonbisnor Which part is failing for you? I think what happens is the build completes and uploads successfully but no `index.html` file is uploaded to Redis.

**Comment by gordonbisnor** [comment]
@jaydev Yes that's it –– do you have the same result?

**Comment by jaydev** [comment]
Ok I merged it. Thanks!

**Comment by gordonbisnor** [comment]
Ok great!

**Pull request merged**
